# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-UTR22
version:      0.14
version_from: 
installdirs:  site
requires:
    Compress::Zlib:                0
    Unicode::Normalize:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
